### ISSUE TITLE
Argument for line-number

### ISSUE THREAD

**Issue by fraserredmond** [shuchkin/PhpStormFG#1]
Thanks for making this, makes life worth living again ;-)

PhpStorm's command-line arguments allow passing in a line-number like so:

```
"c:\Program Files (x86)\JetBrains\PhpStorm 9.0\bin\PhpStorm.exe" C:\git\projectName\  --line 10 "C:\git\projectName\path\to\file.inc"
```

I had a look, and couldn't find documentation for that any more - it used to be on PhpStorm's website, but I guess they've removed it in the help for the new version :-(

Would you be able to provide some way to pass in a line-number to PhpStormFG?

**Comment by shuchkin** [comment]
fixed
https://github.com/shuchkin/PhpStormFG/tree/master/Release
