### ISSUE TITLE
PhpStorm 10.0.2

### ISSUE THREAD

**Issue by fraserredmond** [shuchkin/PhpStormFG#2]
Hi, I just tried PhpStorm 10.0.2, and it still doesn't open in the foreground.... and PhpStormFG doesn't seem to work with it either.

**Comment by shuchkin** [comment]
PhpStormFG.exe like proxy and there supported any version of *Storm (in theory)
But I've also unpredictable behavior sometimes...

**Comment by shuchkin** [comment]
see
https://github.com/shuchkin/PhpStormFG
