### ISSUE TITLE
Old v9 icon in current release

### ISSUE THREAD

**Issue by Toutouwai** [shuchkin/PhpStormFG#4]
From the readme...

> PhpStorm 10 Icon https://github.com/shuchkin/PhpStormFG/blob/master/Release/PhpStormFG.exe
> PhpStorm 9 Icon https://github.com/shuchkin/PhpStormFG/blob/master/Release9/PhpStormFG.exe

But both executables have the same v9 icon. Thought it might have been a Windows IconCache issue, but opening the executable in Resource Hacker shows the old icon embedded.

![2016-02-17_115124](https://cloud.githubusercontent.com/assets/1538852/13093945/d49da776-d56c-11e5-9a05-16294ef5974b.png)

**Comment by shuchkin** [comment]
fixed
