### ISSUE TITLE
Can't open files from Explorer if there is a space in the path

### ISSUE THREAD

**Issue by Toutouwai** [shuchkin/PhpStormFG#6]
When trying to open a file associated with PhpStormFG from Windows Explorer, opening fails with "Cannot find file" if there is a space in the file path. PhpStorm itself can handle paths with spaces.

Thanks for the great tool, BTW. Adds much needed functionality that should have been built into PhpStorm years ago.

**Comment by shuchkin** [comment]
I think u did mistake when associate extension .php and PhpStormFG

**Comment by Toutouwai** [comment]
What makes you think that? Do you mean you can't reproduce this issue?

I think the association is okay - files without spaces in the paths open via PhpStormFG fine, just not if there is a space in the path.

**Comment by shuchkin** [comment]
c:\Path_NO_spaces\index.php - OK
c:\Path With Spaces\index.php - OK

**Comment by Toutouwai** [comment]
I get...
![untitled-4](https://cloud.githubusercontent.com/assets/1538852/14974289/69218fb4-1147-11e6-94e5-5a42c0d5cc0d.png)
...followed by...
![untitled-5](https://cloud.githubusercontent.com/assets/1538852/14974296/783dec90-1147-11e6-853b-bbc4b834055a.png)

Windows 8.1, with PHP files associated with PhpStormFG
![untitled-6](https://cloud.githubusercontent.com/assets/1538852/14974300/84bb3acc-1147-11e6-9845-1180bc8dd0ad.png)

**Comment by Toutouwai** [comment]
I get...
![untitled-4](https://cloud.githubusercontent.com/assets/1538852/14974289/69218fb4-1147-11e6-94e5-5a42c0d5cc0d.png)
...followed by...
![untitled-5](https://cloud.githubusercontent.com/assets/1538852/14974296/783dec90-1147-11e6-853b-bbc4b834055a.png)

Windows 8.1, with PHP files associated with PhpStormFG
![untitled-6](https://cloud.githubusercontent.com/assets/1538852/14974300/84bb3acc-1147-11e6-9845-1180bc8dd0ad.png)

**Comment by Toutouwai** [comment]
If it helps, I can get the file to open by editing the registry key and switching double quotes to single quotes for the %1 variable. But I expect this would introduce problems for file paths that contain apostrophes.
![untitled-8](https://cloud.githubusercontent.com/assets/1538852/14974550/3380c250-114a-11e6-98ca-dc58494483ef.png)

**Comment by shuchkin** [comment]
I think u did mistake when associate extension .php and PhpStormFG === I think Win8 did mistake when associate extension .php and PhpStormFG

in win7 is ok

**Comment by shuchkin** [comment]
FIXED
